name: enumerable
version: 0.0.1
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Enumerable collections for Dart language (inspired by Microsoft LINQ).
homepage: https://github.com/mezoni/enumerable
environment:
  sdk: '>=2.6.0-dev.7.0 <3.0.0'
dependencies:  
dev_dependencies:  
  pedantic: ^1.8.0
  test: ^1.8.0
